[package]
name = "diff-kit"
version = "0.1.0"
authors = ["David L. L. Thomas <davidleothomas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidiff = "0.3.3"
json = "0.12.4"
